# HomeWork

In [240]:
import numpy as np
import pandas as pd

### Câu 1

In [241]:
A = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
])

print(A)

[[1 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 1]]

##### 1

In [242]:
print("Rank của ma trận A:", np.linalg.matrix_rank(A))

Rank của ma trận A: 2

Rank của ma trận $A$ (2) bé hơn số cột của ma trận $A$ (3) -> các cột của $A$ phụ thuộc tuyến tính

##### 2

In [243]:
print("Kết quả:")
A_t = A.T @ A
print(A_t)

Kết quả:
[[2 0 2]
 [0 2 2]
 [2 2 4]]

##### 3

In [244]:
eigenvalues, eigenvectors = np.linalg.eigh(A_t) 
print("Eigenvalues:", np.round(eigenvalues, 2))
print("Eigenvectors:")
print(np.round(eigenvectors, 2))

Eigenvalues: [0. 2. 6.]
Eigenvectors:
[[-0.58 -0.71 -0.41]
 [-0.58  0.71 -0.41]
 [ 0.58 -0.   -0.82]]

##### 4

In [245]:
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]
print("Sau khi sắp xếp:")
print("Eigenvalues:", np.round(eigenvalues, 2))
print("Eigenvectors:")
print(np.round(eigenvectors, 2))

Sau khi sắp xếp:
Eigenvalues: [6. 2. 0.]
Eigenvectors:
[[-0.41 -0.71 -0.58]
 [-0.41  0.71 -0.58]
 [-0.82 -0.    0.58]]

##### 5

In [246]:
sigularvalues = np.round(np.sqrt(eigenvalues))
print("Singular values:")
print(np.round(sigularvalues))

Singular values:
[2. 1. 0.]

##### 6

In [247]:
print("Ở đây singular vectors chính là eigenvectors (do dùng hàm eigh thay vì eig)")
singularvectors = eigenvectors
print("Singularvectors:")
print(np.round(singularvectors, 2))

Ở đây singular vectors chính là eigenvectors (do dùng hàm eigh thay vì eig)
Singularvectors:
[[-0.41 -0.71 -0.58]
 [-0.41  0.71 -0.58]
 [-0.82 -0.    0.58]]

##### 7

In [248]:
U = []
for i in range(len(sigularvalues)):
    if sigularvalues[i] == 0:
        continue
    tmp = (A @ singularvectors[:, i]) / sigularvalues[i]
    U.append(tmp)
U = np.column_stack(U)
print(np.round(U))

[[-1. -1.]
 [-1.  1.]
 [-1. -1.]
 [-1.  1.]]

##### 8

In [249]:
Q, R = np.linalg.qr(
    np.column_stack([
        U,
        np.eye(4)
    ])
)
U = np.column_stack([U, Q[:,2:4]])

sigma = np.zeros((A.shape[0], A.shape[1]))

for i in range(len(sigularvalues)):
    sigma[i, i] = sigularvalues[i]

print("U hoàn chỉnh:")
print(np.round(U))
print("Sigma:")
print(np.round(sigma))
print("V:")
print(np.round(eigenvectors))

U hoàn chỉnh:
[[-1. -1.  1.  0.]
 [-1.  1. -0. -1.]
 [-1. -1. -1.  0.]
 [-1.  1. -0.  1.]]
Sigma:
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
V:
[[-0. -1. -1.]
 [-0.  1. -1.]
 [-1. -0.  1.]]

##### 9

In [250]:
A_n = U @ sigma @ eigenvectors.T
print(A)

[[1 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 1]]

##### 10

In [251]:
print("Shape U:", U.shape)
print("Shape Sigma:", sigma.shape)
print("Shape V^T:", eigenvectors.T.shape)

Shape U: (4, 4)
Shape Sigma: (4, 3)
Shape V^T: (3, 3)

##### 11

In [252]:
print("Kiểm tra U^T U:")
print(np.round(U.T @ U, 2))
print()


print("Kiểm tra V^T V:")
print(np.round(eigenvectors.T @ eigenvectors, 2))
print()

print("Kiểm tra U Sigma V^T:")
A_reconstructed = U @ sigma @ eigenvectors.T
print()
print(np.round(A_reconstructed, 2))

Kiểm tra U^T U:
[[ 1.5  0.   0.   0. ]
 [ 0.   2.  -0.  -0. ]
 [ 0.  -0.   1.   0. ]
 [ 0.  -0.   0.   1. ]]

Kiểm tra V^T V:
[[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]

Kiểm tra U Sigma V^T:

[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]]

##### 12. Giải thích

- Vì $rank(A)=2<3$, nên chỉ có 2 singular values khác 0 và một singular value bằng 0.

- Vector $v_i$ ứng với $\sigma_i=0$ thỏa $Av_i=0$, nên $v_i$ thuộc null space của $A$.

- Vì các thành phần có $\sigma_i=0$ đóng góp bằng 0 nên có thể loại bỏ mà không làm thay đổi $A$.

### Câu 2

In [253]:
sigma = np.array([12, 5, 3, 1])

##### 1
Hạng của ma trận là 4 vì có 4 singular values khác 0

##### 2

In [254]:
print("Tổng năng lượng:", (sigma**2).sum())

Tổng năng lượng: 179

##### 3

In [255]:
R = []
nangluonggiulai = []
for k in range(1, 5):
    tmp = ((sigma[:k]**2).sum()) / ((sigma**2).sum())
    nangluonggiulai.append((sigma[:k]**2).sum())
    R.append(tmp)
nangluonggiulai = np.array(nangluonggiulai)
R = np.array(R)
print(R)
print(nangluonggiulai)

[0.80446927 0.94413408 0.99441341 1.        ]
[144 169 178 179]

##### 4

In [256]:
table1 = pd.DataFrame({
    "k": range(1, 5),
    "Năng lượng giữ lại":nangluonggiulai,
    "R(x)":R
})
display(table1)

   k  Năng lượng giữ lại      R(x)
0  1                 144  0.804469
1  2                 169  0.944134
2  3                 178  0.994413
3  4                 179  1.000000

##### 5

In [257]:
du = []
for k in range(1,4):
    du.append(np.sqrt((sigma[k:]**2).sum()))
du = np.array(du)
print(du)

[5.91607978 3.16227766 1.        ]

##### 6

In [258]:
table2 = pd.DataFrame({
    "k": range(1, 4),
    "R(x)": R[:3],\
    "|X-X_k|_F":du
})
display(table2)

   k      R(x)  |X-X_k|_F
0  1  0.804469   5.916080
1  2  0.944134   3.162278
2  3  0.994413   1.000000

##### 8
Chọn k = 3, vì:
- R(x) tương đương 1
- Sai rất thấp

##### 9
- Singular values phải sắp xếp giảm dần vì Singular value càng lớn thì càng chứa nhiều thông tin
- Giữ nhiều singular values thì sẽ giảm sai số, giữ nhiều thông tin hơn. Tuy nhiên sẽ tốn bộ nhớ, thời gian tính toán
- K lớn: tỷ lệ năng lượng cao, sai số nhỏ, dữ liệu gần giống ma trận gốc, nhưng khả năng nén thấp, tốn bộ nhớ và thời gian tính toán hơn. K nhỏ: nén dữ liệu tốt, giảm chi phí lưu trữ và tính toán, có thể loại bỏ nhiễu, nhưng mất nhiều thông tin hơn, sai số xấp xỉ tăng.